2023-11-20 04:42:55,884 ERROR: Exception on /admin_panel_main [GET] [in c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\abifa\Desktop\Brainfor\app\main\admin_panel\admin_routes.py", line 16, in admin_panel_main
    return render_template('admin_panel/admin_panel_main.html', infos=infos)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\abifa\Desktop\Brainfor\app\templates\admin_panel\admin_panel_main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\abifa\Desktop\Brainfor\app\templates\base.html", line 35, in top-level template code
    {% block app_content %}
  File "C:\Users\abifa\Desktop\Brainfor\app\templates\admin_panel\admin_panel_main.html", line 13, in block 'app_content'
    <a href="{{ url_for('create_new_student') }}"> Create new student</a>
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'create_new_student'. Did you mean 'auth.reset_password_request' instead?
2023-11-20 04:43:50,389 ERROR: Exception on /admin_panel_main [GET] [in c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\abifa\Desktop\Brainfor\app\main\admin_panel\admin_routes.py", line 16, in admin_panel_main
    return render_template('admin_panel/admin_panel_main.html', infos=infos)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\abifa\Desktop\Brainfor\app\templates\admin_panel\admin_panel_main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\abifa\Desktop\Brainfor\app\templates\base.html", line 35, in top-level template code
    {% block app_content %}
  File "C:\Users\abifa\Desktop\Brainfor\app\templates\admin_panel\admin_panel_main.html", line 13, in block 'app_content'
    <a href="{{ url_for('main.add_new') }}"> Create new student</a>
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'create_new_student'. Did you mean 'auth.reset_password_request' instead?
2023-11-20 04:43:54,555 ERROR: Exception on /admin_panel_main [GET] [in c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\abifa\Desktop\Brainfor\app\main\admin_panel\admin_routes.py", line 16, in admin_panel_main
    return render_template('admin_panel/admin_panel_main.html', infos=infos)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\abifa\Desktop\Brainfor\app\templates\admin_panel\admin_panel_main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\abifa\Desktop\Brainfor\app\templates\base.html", line 35, in top-level template code
    {% block app_content %}
  File "C:\Users\abifa\Desktop\Brainfor\app\templates\admin_panel\admin_panel_main.html", line 13, in block 'app_content'
    <a href="{{ url_for('main.add_new') }}"> Create new student</a>
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'create_new_student'. Did you mean 'auth.reset_password_request' instead?
2023-11-25 09:31:17,402 INFO: Microblog startup [in C:\Users\abifa\Desktop\Brainfor\app\__init__.py:57]
2023-11-25 09:31:24,226 ERROR: Exception on /admin_users [GET] [in c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\users\abifa\desktop\brainfor\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\abifa\Desktop\Brainfor\app\main\admin_panel\admin_routes.py", line 53, in admin_users
    users = User.queryjoin(Info).filter(User.role < current_user.role).all()
AttributeError: type object 'User' has no attribute 'queryjoin'
2024-01-08 16:07:34,633 INFO: Microblog startup [in C:\Users\abifa\Desktop\Brainfor\app\__init__.py:57]
